import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { LogoIcon } from '@/utils/icons'
import Button from '@/components/ui/CustomButton'
import { useState } from 'react'
import PaymentCard from '@/components/paymentCard'
import { NftType } from '@/types/nftType.type'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [step, setStep] = useState(0);
  const [nft, setNft] = useState<NftType | undefined>(undefined)

  const getNftDetail = () => {

    fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL ?? ""}project/float/nft-sale-details`, {
      headers: {
        'x-api-key': process.env.NEXT_PUBLIC_API_KEY ?? ""
      }
    })
      .then(response => response.json())
      .then(data => { console.log(data); setNft(data); setStep(1) })
      .catch(error => console.error(error));
  }

  return (
    <>
      <Head>
        <title>Payglide Payment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.TitleSection}>
            <LogoIcon width="649px" height="175px" style={{ textAlign: "start", marginTop: "4rem" }} />
            <Image src="/descriptionTitle.png" alt="flow" width={763} height={63} />
            <div className={styles.btnContainer}>
              <Button
                color="black"
                onClick={() => { }}
                width="300px"
                height="60px"
                fontSize={20}
                fontWeight={500}
                bgColor='#7EB2FF'
                text={"Join Waitlist"}
              ></Button>
            </div>
          </div>
          {step === 0 && (
            <div className={styles.paymentSection}>
              <div>
                <p className={styles.tryNowTitle}>TRY NOW!</p>
                <p className={styles.tryNowDescription}>BUY FIRST EVER FLOW NFT DIRECT WITH CARD PAYMENT</p>
                <div>
                  <Button
                    color="white"
                    onClick={() => { getNftDetail(); }}
                    width="100%"
                    height="264px"
                    fontSize={20}
                    fontWeight={500}
                    bgColor='#0C8909'
                    text={"WALLETLESS UI"}
                  ></Button>
                </div>
              </div>
            </div>
          )}
          {(!!nft) && (
            <div className={styles.paymentCardSection}>
              <PaymentCard step={step} onStepChange={setStep} nft={nft} />
              <p className={styles.stepText}>{
                step == 1 ? "CLICK PAY WITH CARD" :
                  step == 2 ? "ENTER ADDRESS AND CLICK NEXT" :
                    step == 3 ? "ENTER CARD DETAILS AND CLICK REVIEW" :
                      step == 4 ? "CHECK TERMS BOX AND CLICK PAY" :
                        "END OF PURCHASE"
              }</p>
            </div>
          )}
        </div>
      </main>
    </>
  )
}
