import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Button from '@/components/ui/CustomButton'
import { useEffect, useState } from 'react'
import PaymentCard from '@/components/paymentCard'
import { NftType } from '@/types/nftType.type'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [step, setStep] = useState(1);
  const [nft, setNft] = useState<NftType | undefined>(undefined)

  const getNftDetail = () => {

    fetch(`${process.env.NEXT_PUBLIC_BACKEND_URL ?? ""}project/float/nft-sale-details`, {
      headers: {
        'x-api-key': process.env.NEXT_PUBLIC_API_KEY ?? ""
      }
    })
      .then(response => response.json())
      .then(data => { console.log(data); setNft(data); setStep(1) })
      .catch(error => console.error(error));
  }

  const scrollToNextViewHeight = () => {
    const element = document.getElementById("paymentCardSection");
    if (element) {
      element.scrollIntoView({ behavior: "smooth", block: "start", inline: "nearest" });
    }
  }

  useEffect(() => {
    getNftDetail();
  }, [])

  return (
    <>
      <Head>
        <title>Payglide Payment</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.TitleSection}>
            <div className={styles.textContainer}>
              <Image src="/payGlide-logo.png" alt="flow" width={276} height={58} style={{ marginBottom: "3rem" }} />
              <p className={styles.mainTitle}>Freedom of Payments</p>
              <p className={styles.mainTitleDescription}>PayGlide enables direct fiat to NFT payments onFLOW blockchain</p>
              <div className={styles.btnContainer}>
                <div className={styles.firstHomeBtn}>
                  <Button
                    color="white"
                    onClick={() => { }}
                    width="230px"
                    height="60px"
                    fontSize={20}
                    fontWeight={700}
                    bgColor='black'
                    text={"JOIN WAITLIST"}
                    borderRadius={15}
                  ></Button>
                </div>
                <div>
                  <Button
                    color="white"
                    onClick={() => { scrollToNextViewHeight() }}
                    width="230px"
                    height="60px"
                    borderRadius={15}
                    fontSize={20}
                    fontWeight={700}
                    bgColor='#BF3DDB'
                    text={"TRY DEMO"}
                  ></Button>
                </div>
              </div>
            </div>
            <div className={styles.bottomSection}>
              <div style={{ marginRight: 50 }}>
                <p className={styles.bottomSectionTitle}>Privacy Policy</p>
              </div>
              <div>
                <p className={styles.bottomSectionTitle}>PayGlide © 2022</p>
              </div>
            </div>
          </div>
          {(!!nft) && (
            <div className={styles.paymentCardSection} id="paymentCardSection">

              <p className={styles.demoText} style={{ color: "white" }}>DEMO ON TESTNET</p>
              <PaymentCard step={step} onStepChange={setStep} nft={nft} />
              {/* <div className={styles.bottomSectionBtn}>
                <Button
                  color="white"
                  onClick={() => { }}
                  width="65%"
                  height="60px"
                  borderRadius={15}
                  fontSize={20}
                  fontWeight={700}
                  bgColor='#BF3DDB'
                  text={"CREATE FLOAT CHECKOUT"}
                ></Button>
              </div> */}
            </div>
          )}
        </div>
      </main>
    </>
  )
}
